name: Sync Staging with Main

on:
  push:
    branches:
      - main
  workflow_dispatch: # Enable manual triggering

jobs:
  sync-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'refs/heads/main' # Explicitly checkout main branch

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # You can specify Node.js version 14 or higher

      - name: Create staging branch if it doesn't exist
        run: |
          git fetch origin main
          git checkout -B staging origin/main

      - name: Push changes to staging
        run: |
          git push --force-with-lease origin staging
